name: Pull Request Checks
on: pull_request

jobs:
  build:
    name: Build PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk
          architecture: x64

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install atlassian-plugin-sdk
        run: |
          wget -nv https://packages.atlassian.com/api/gpg/key/public
          sudo apt-key add public
          sudo sh -c 'echo "deb https://packages.atlassian.com/atlassian-sdk-deb stable contrib" >> /etc/apt/sources.list'
          sudo apt-get -q update
          sudo apt-get -q -y install atlassian-plugin-sdk

      - name: Build packages
        run: |
          atlas-package --batch-mode
          mkdir artifacts/
          mv target/prism-* artifacts/

      - uses: actions/upload-artifact@v1
        with:
          name: packages
          path: artifacts/